services:
    publisher-api:
        image: publisher-api:${TAG:-latest}
        build:
            context: src/PublisherApi/.
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - Redis__Host=redis_db
        ports:
            - 5000:5000
        healthcheck:
            test: curl --fail -s http://publisher-api:5000/api/HealthCheck || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        depends_on:
            - redis_db

    redis_db:
        image: redis
        container_name: cache
        ports:
        - "6379:6379"
        restart: unless-stopped
        volumes:
        - redis_volume:/data

volumes:
    redis_volume: